plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.5'
    id 'maven-publish'
}

version = project.mod_version
group = "io.github.itsfelix5"

base {
    archivesName = "CameraTweaks"
}

repositories {
    maven {
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        url = "https://maven.quiltmc.org/repository/release/"
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:+"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/cameratweaks.accesswidener")
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_CameraTweaks" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = "CameraTweaks"
            from components.java
        }
    }
}